name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
    - name: Send Greeting
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Hey there! 👋 Thanks for opening this issue. We truly appreciate your effort to make our project better. 
          Our team will review your issue shortly. Meanwhile, feel free to provide any additional details or comments 
          that might help us address it faster. Have a great day! 🌟
        pr-message: >
          Hello and welcome! 🎉 Thanks for submitting this pull request. Your contribution helps us improve and grow this project.
          Our team will review your PR as soon as possible. While you wait, why not check out other parts of the repo or share your thoughts 
          on improvements? We’re glad to have you on board! 🚀
